### ISSUE TITLE
RuntimeError: input.is_contiguous()

### ISSUE THREAD

**Issue by WurmD** [kchengiva/Shift-GCN#28]
Hi, did this ever happen to you?
> RuntimeError: input.is_contiguous() INTERNAL ASSERT FAILED at "shift_cuda.cpp":21, please report a bug to PyTorch. input must be contiguous

Full trace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/home/dario/.vscode-server/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/mnt/home/dario/.vscode-server/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/mnt/home/dario/.vscode-server/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dario/SynSE/synse/load_shiftgcn_network.py", line 46, in <module>
    output = model(fp)
  File "/home/dario/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dario/SynSE/synse/shiftgcn/model/shift_gcn.py", line 200, in forward
    x = self.l1(x)
  File "/home/dario/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dario/SynSE/synse/shiftgcn/model/shift_gcn.py", line 161, in forward
    x = self.tcn1(self.gcn1(x)) + self.residual(x)
  File "/home/dario/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dario/SynSE/synse/shiftgcn/model/shift_gcn.py", line 68, in forward
    x = self.shift_in(x)
  File "/home/dario/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./shiftgcn/model/Temporal_shift/cuda/shift.py", line 45, in forward
    return ShiftFunction.apply(input,self.xpos,self.ypos,self.stride)
  File "./shiftgcn/model/Temporal_shift/cuda/shift.py", line 19, in forward
    output = shift_cuda.forward(input,xpos,ypos,stride)
RuntimeError: input.is_contiguous() INTERNAL ASSERT FAILED at "shift_cuda.cpp":21, please report a bug to PyTorch. input must be contiguous
```

Input `fp`:
```
tensor([[[[[-0.0102,  0.0000],
           ...,
           ...,
           [ 0.3775,  0.0000]]]]], device='cuda:0')
requires_grad:False
shape:torch.Size([1, 3, 300, 25, 2])
```

**Comment by Droppledev** [comment]
I had the same problem but I found the solution

The error happened in the `./model/Temporal_shift/cuda/shift.py` and from the error, we know that the input must be contiguous
The simple solution is to convert the input to be contiguous first with:
`input = input.contiguous()`
before this line
`output = shift_cuda.forward(input,xpos,ypos,stride)`

Here is the [reference](https://github.com/alexandrosstergiou/SoftPool/issues/6)

Hope it helps 😄

**Comment by WurmD** [comment]
Indeed it works! Thanks!

**Comment by ikuta23** [comment]
> I had the same problem but I found the solution
> 
> The error happened in the `./model/Temporal_shift/cuda/shift.py` and from the error, we know that the input must be contiguous The simple solution is to convert the input to be contiguous first with: `input = input.contiguous()` before this line `output = shift_cuda.forward(input,xpos,ypos,stride)`
> 
> Here is the [reference](https://github.com/alexandrosstergiou/SoftPool/issues/6)
> 
> Hope it helps 😄

You're a genius! Thanks so much!
