### ISSUE TITLE
RuntimeError: Only Tensors of floating point dtype can require gradients

### ISSUE THREAD

**Issue by BrownStorm** [kchengiva/Shift-GCN#29]
您好
我在使用两张卡运行时会出现这个错误：

Traceback (most recent call last):
  File "main.py", line 541, in <module>
    processor.start()
  File "main.py", line 482, in start
    self.train(epoch, save_model=True)
  File "main.py", line 370, in train
    output = self.model(data)
  File "/home/Liutl/anaconda3/envs/sgcn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Liutl/anaconda3/envs/sgcn/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 151, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/home/Liutl/anaconda3/envs/sgcn/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 156, in replicate
    return replicate(module, device_ids, not torch.is_grad_enabled())
  File "/home/Liutl/anaconda3/envs/sgcn/lib/python3.7/site-packages/torch/nn/parallel/replicate.py", line 146, in replicate
    setattr(replica, key, Parameter(param))
  File "/home/Liutl/anaconda3/envs/sgcn/lib/python3.7/site-packages/torch/nn/parameter.py", line 26, in __new__
    return torch.Tensor._make_subclass(cls, data, requires_grad)
RuntimeError: Only Tensors of floating point dtype can require gradients

您知道如何解决么？

**Comment by DannyFengFeng** [comment]
I also encountered this problem. Have you solved it？

**Comment by DannyFengFeng** [comment]
是不是torch版本的问题？我换了个torch版本就不出现这个问题了。

**Comment by BrownStorm** [comment]
> 是不是torch版本的问题？我换了个torch版本就不出现这个问题了。

请问你用的是什么版本？

**Comment by DannyFengFeng** [comment]
> > 是不是torch版本的问题？我换了个torch版本就不出现这个问题了。
> 
> 请问你用的是什么版本？

1.3.1
